language: node_js
node_js:
- '6'
install:
- travis_retry $TRAVIS_BUILD_DIR/go setup
script:
- "$TRAVIS_BUILD_DIR/go test"
after_success:
- cd $TRAVIS_BUILD_DIR/backend
- "./lein deploy clojars"
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.lein"
env:
  global:
    #LEIN_PASSWORD (testing)
    secure: kKHhoUrEPsV6r15rtK2OLHCMJkYBdOyLDZ9NiaCUfY46qXLJyVQtUqS7qep8hkWaBcz5jRiaBN2K7m8mNO1VKuFvOzootgHSwsXOj9247xtw7pVI5Uu4QUkHNpIJPkTLufd3gd75EO0jcgOeEI0LqtpCphAQBTwpG7QWo8CH/DLfmQokOm0DxMwdh81ZEu4tCsLV2vaYvzQo2BgVPTPsgk2m4FA3KOZrkSJbLgaHMIINaajoQ6wq2/t+N5ys38sr1KML6Hm6ej/QmpO+sCsqY/RVvDBKpJ+S4KhUP7cgTTkkmq+JDg8IEyA6GplaacSpDYxZCR0gZm014PFYFpztFnpGzeARfpdBOLvlSrr31K9mKedbHrSfpeYTNXa4dqRpRBrW6M/slXse3/4GapbemnpvdGXheRPQkq5/cirJ0UZGfOEBWhjnBh5JkMNJ5c3/u/nBq89K3aKKTpLYdD8Kt/kcHbFge4inmgvgr7av12AbBwszMJ1wAs6xK7Nt7uSol2taxFr/e1gxX6+6NZEHdm/3823ELerBfNf0tI4yCa5TWU+3rXrYJq/7IsP9n8kkIAJisuvNqKBmdtQIzdzEvZcTE5hQqZ8VyS3nFAyY+zXuMG3cc3emguKyAhii464lDgqsqdpGVhem9e+0f+UdBifNHYwXYxml/7h9l8Q0deM=
